### ISSUE TITLE
How to use OcrParserProvider to parse PNG and JPG files

### ISSUE THREAD

**Issue by UserZhangXiaoZhe** [docwire/docwire#124]
MacOS Xcode 15.2

<img width="1406" alt="企业微信截图_9e59d702-a0ac-4143-bb30-fd2d70e255b4" src="https://github.com/docwire/docwire/assets/8394283/2f32707d-070d-4d51-a0fd-04295884e5c9">

Doc, ppt, and log can be parsed, but png and jpg have failed

**Comment by as-ascii** [comment]
Thank you for your report. This is because the SDK is assuming that all files including resource files are in vcpkg-like directory hierarchy. If the SDK binaries are stored in "<DIR>/bin" or "<DIR>/tools", all resources are expected to be in "<DIR>/share", so relative access path is "../share".
To find <DIR> where SDK binaries are located, the SDK tries all directories in $PATH on Windows, in $DYLD_FALLBACK_LIBRARY_PATH on MacOSX and $LD_LIBRARY_PATH on Linux and others.
If you don't use these variables and shared libraries are loaded using compiled-in rpath or are just relocated manually there is a problem with loading resources.
For OCR process you can also try to set a TESSDATA_PREFIX environment variable to absolute path to vcpkg/installed/x64-linux-dynamic/share/tessdata-fast but it is better to allow all resources to be located correctly.
We are still trying to figure out the best way to find path to resources and tried several methods already. If you have any suggestions how to improve user experience is this area, feel free to write them here.

Best regards.

**Comment by UserZhangXiaoZhe** [comment]
Thank you very much！
Tesseract OCR needs to configure environment variables in xcode:
DYLD_FALLBACK_LIBRARY_PATH:
~/docwire/docwire-2024.04.04/installed/arm64-osx-dynamic/share/tesseract

TESSDATA_PREFIX:
~/docwire/docwire-2024.04.04/installed/arm64-osx-dynamic/share/tessdata-fast

![image](https://github.com/docwire/docwire/assets/8394283/0a4f50a7-8e8e-4bba-9341-9a967ef37b8d)
