### ISSUE TITLE
Crash in docwire while parsing html file

### ISSUE THREAD

**Issue by pcoramasionwu** [docwire/docwire#127]
We are using version 2024.04.04 of docwire, which still seems to be the latest version.

The code is crashing at line 392 of plain_text_writer.cpp. In this case, 'table' (which is a vector) contains no elements, so the back() method crashes.

      else if (std::holds_alternative<tag::TableCell>(tags[i]))
      {
        table.back().push_back(Cell());
      }

sample html file (please unzip)
[readme.zip](https://github.com/docwire/docwire/files/15438903/readme.zip)

**Comment by as-ascii** [comment]
The problem is because of "thead" tag in the sample file. It contains "td" tags directly. According to the html specification it should contain "tr" tags inside, not "td" directly. The protection against this kind of standard violations will be implemented and automatic test will be added. Estimated time to merge the fix is around 1 day.
