### ISSUE TITLE
XML conversion includes tags in the converted output

### ISSUE THREAD

**Issue by efieleke-tausight** [docwire/docwire#141]
I used Word to convert docx files to XML. They open and display fine in Word, however docwire includes the tags when converting such documents to text.

I have attached the .xml file as well as the conversion results. Here is the code we use to perform the conversion. In this case, GetMappedExtension is returning "xml":

```
auto iStream = std::make_shared<boost::iostreams::stream<boost::iostreams::array_source>>(buffer, bufferSize);

docwire::data_source dataSource(
	docwire::seekable_stream_ptr { iStream },
	docwire::file_extension("." + GetMappedExtension(extension)));

std::basic_stringstream<char> outStream;

std::move(dataSource) | 
	docwire::ParseDetectedFormat<docwire::OfficeFormatsParserProvider, docwire::MailParserProvider, docwire::OcrParserProvider>(_parameters) |
	docwire::PlainTextExporter() |
	outStream;
```

**Comment by efieleke-tausight** [comment]
[0_ea-2a_1108..zip](https://github.com/user-attachments/files/16265725/0_ea-2a_1108.zip)

**Comment by as-ascii** [comment]
The problem is that "XML" is very general format so "XML" extension hint is not very helpful.

The second problem is that even if whole document text is send to ParseDetectedFormat it failes to detect Word format. This one needs more analysis as FODT, the similar single-xml file for Open/LibreOffice is working fine.

**Comment by pcoramasionwu** [comment]
Expected Outcome: The plaintext exporter should output XML documents as they would be exported in MS Word. 

eg:

![image](https://github.com/user-attachments/assets/3e4cfdfa-a0aa-4354-9ffa-988e8b1a93ba)

**Comment by as-ascii** [comment]
The specialized XMLParser class was added to the SDK that handles XML files in general (those that are not classified as ODF or OOXML formats). It is available in docwire_xml library. docwire_office_formats links it as well. It handles "xml" file extension that previously was handled by TXTParser. When detecting "by data" the correct xml header ("<?xml") is expected at the beginning of the file.

XMLParser parses XML file and sends all text nodes as docwire::tag::Text structures. Tag names are not presented in the output and in addition "style" subtree is skipped if found.

Automatic test (CI) was added with xml document exactly as presented on the screenshot and the plain text output is:
```
This is a Heading


                        This is a standard paragraph. It includes detailed information and can span multiple lines or pages, depending on content length.
```
that is (we believe) better that on the screenshot (font sizes and font names removed).

Tabs and new line characters are preserved. It can be discussed, but we believe that it is better to present more whitespaces than to glue words or sentences together.

**Comment by efieleke-tausight** [comment]
I tested this against the file attached to this ticket. The conversion returned a string with only a single new line. If the attached XML file is opened in Word, you will see that it contains a great deal of text. I think this should be re-opened.

**Comment by as-ascii** [comment]
Ok it seems that upgraded libxml2 behave a little bit different in corner cases and the problem is in parsing additional <? ... ?> pseudo-tags ("xml processing instructions").
We have a workaround for this and in addition added some special rules of w:p and w:tab tags to add additional whitespaces in the output that prevents merging of some words in your document (and others as well).
We will merge the fix as a new release probably today later or tomorrow.

**Comment by as-ascii** [comment]
In future, when format detection will be improved, that kind of Word files with xml extension should go to proper OOXML parser.
