### ISSUE TITLE
docwire removes empty lines from txt files

### ISSUE THREAD

**Issue by efieleke-tausight** [docwire/docwire#146]
I have attached a text file. When converted by docwire, you will see that a number of blank lines are removed. Not sure if this is a regression introduced by recent changes.

[02eounrel.txt](https://github.com/user-attachments/files/16820364/02eounrel.txt)

**Comment by as-ascii** [comment]
As described in the issue https://github.com/docwire/docwire/issues/140 in default configuration the TXTParser is detecting the paragraphs and converting them into internal tag::Paragraph and tag::CloseParagraph. PlainTextExporter is converting it back to plain text and it is possible that multiple lines separating two paragraphs will be converted/normalized to the single one.

To disable this conversion (that is very important for other exporters like html, because then proper output structure will be emitted) additional parser parameters can be used, like in this automatic test:
https://github.com/docwire/docwire/blob/31a87223f07b9c2e4ead509ebb43468d8a9d2498/tests/api_tests.cpp#L1259-L1269
When parsing paragraphs is disabled, only end-of-line normalization is performed. It can be disabled as well if required:
https://github.com/docwire/docwire/blob/31a87223f07b9c2e4ead509ebb43468d8a9d2498/tests/api_tests.cpp#L1195-L1211
Multiple parameters can be passed, using += operator like here:
https://github.com/docwire/docwire/blob/31a87223f07b9c2e4ead509ebb43468d8a9d2498/tests/api_tests.cpp#L1213

**Comment by efieleke-tausight** [comment]
Thanks for the info. This can be closed (in my opinion).
